name: Alternate Build iOS IPA

on:
  push:
    branches:
      - main

env:
  IONIC_CLI_VERSION: 6.20.8
  NODE_VERSION: 19.5.0
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install gpg
      run: brew install gnupg
    
    - name: Setup provisioning profile
      run: ./.github/secrets/decrypt_secrets.sh
      env:
        IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }} 
    
    - name: Install Ionic CLI
      run: |
        npm install -g ionic
        ionic config set -g daemon.updates false
    - name: Install dependencies
      run: npm install npm@9.3.1 -g
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli@4.4.0
      
    - name: Install Cocoapods
      run: sudo gem install cocoapods

    - name: Cache Pods dependencies
      uses: actions/cache@v1
      with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-
    - name : Install Legacy-peer-deps
      run: sudo npm install react-scripts --legacy-peer-deps
      
    - name : Install awesome-cordova-plugins
      run : sudo npm i @awesome-cordova-plugins/core    
    
    - name: Build iOS IPA
      run: sudo npm run build-prod
      env: 
       CI: true
       
    - name: Capacitor commands   
      run: |
        npx cap add ios
        npx cap sync ios
        npx cap open ios      
   
   
    - name: Build app
      run: |
          cd ios/App/ && xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=13.0 \
            PROVISIONING_PROFILE="profile" \
            CODE_SIGN_IDENTITY="Apple Development: Indulekha Singh (J46QJZ7FLK)" 
            DEVELOPMENT_TEAM='2A43T2JL46'
            
    - name: Export app
      run: |
          cd ios/App/ && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist $PWD/ci.plist \
            -exportPath $PWD/build
          
    - name: Deploy IPA
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ~/App.ipa
