name: Alternate Build iOS IPA

on:
  push:
    branches:
      - master

env:
  IONIC_CLI_VERSION: 6.20.3
  NODE_VERSION: 18.12.1
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install gpg
      run: brew reinstall gnupg
      
    - name: Setup provisioning profile
      run: chmod +x ./.github/secrets/decrypt_secrets.sh
      env:
        IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }} 
    
    - name: Install Ionic CLI
      run: |
        npm install -g ionic
        ionic config set -g daemon.updates false
        
    - name: Install dependencies
      run: npm install npm@9.3.1 -g
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli@4.4.0
      
    - name: Install Cocoapods
      run: sudo gem install cocoapods
      
    - name: Cache Pods dependencies
      uses: actions/cache@v1
      with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-
            
    - name : Install Legacy-peer-deps
      run: sudo npm install react-scripts --legacy-peer-deps
      
    - name : Install awesome-cordova-plugins
      run : sudo npm i @awesome-cordova-plugins/core
